; #############################################################################

    #ifndef _FEMTOPASS_INC_
    #define _FEMTOPASS_INC_
    ;{

; #############################################################################

        #define MAX_PASSWORD                80h

; =============================================================================

        #define NULL                         0h

        #define GENERIC_READ          80000000h
        #define GENERIC_WRITE         40000000h

        #define FILE_SHARE_READ              1h
        #define OPEN_EXISTING                3h
        #define FILE_ATTRIBUTE_NORMAL       80h

        #define ENABLE_ECHO_INPUT            4h
        #define CP_UTF8                  0FDE9h

        #define STD_OUTPUT_HANDLE          -11

; =============================================================================

    ;}
    #endif // _FEMTOPASS_INC_

; #############################################################################
